version: '3.1'
services:
  web:
    container_name: ${WEB_IMAGE_NAME}
    image: oddo:${WEB_IMAGE_TAG}
    build: ./
    depends_on:
      - db
    ports:
      - "${WEB_PORT}:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./addons-customize:/mnt/extra-addons-customize
      - ./logs:/var/log/odoo
    environment:
      - HOST=db
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWD}
  db:
    container_name: postgres_odoo
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-db-data:
  odoo-web-data: